CREATE DATABASE IF NOT EXISTS MyDB;
CREATE  USER 'myuser'@'localhost' IDENTIFIED BY 'TtGm!123';
GRANT ALL PRIVILEGES ON MyDB.* TO 'myuser'@'localhost' IDENTIFIED BY 'TtGm!123' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON MyDB.* TO 'myuser'@'192.168.33.10' IDENTIFIED BY 'TtGm!123' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON MyDB.* TO 'myuser'@'%' IDENTIFIED BY 'TtGm!123' WITH GRANT OPTION;
FLUSH PRIVILEGES;